name: fco2diffusion
channels:
  - conda-forge
dependencies:
  - pip=24.1
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alembic=1.11.1
  - anyio=3.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - async-lru=2.0.2
  - async_generator=1.10
  - attrs=23.1.0
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.12.2
  - bleach=6.0.0
  - blinker=1.6.2
  - boltons=23.0.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - certipy=0.1.3
  - cffi=1.15.1
  - charset-normalizer=3.1.0
  - colorama=0.4.6
  - comm=0.1.3
  - conda=23.3.1
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.8.0
  - configurable-http-proxy=4.5.4
  - cryptography=40.0.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=1.2.0
  - flit-core=3.9.0
  - fmt=9.1.0
  - greenlet=2.0.2
  - icu=72.1
  - idna=3.4
  - importlib-metadata=6.6.0
  - importlib_metadata=6.6.0
  - importlib_resources=5.12.0
  - ipython=8.13.2
  - ipython_genutils=0.2.0
  - jedi=0.18.2
  - json5=0.9.5
  - jsonpatch=1.32
  - jsonpointer=2.0
  - jsonschema=4.17.3
  - jupyter-lsp=2.1.0
  - jupyter_client=8.2.0
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=2.6.0
  - jupyter_server_terminals=0.4.4
  - jupyter_telemetry=0.1.0
  - jupyterhub=4.0.0
  - jupyterhub-base=4.0.0
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.22.1
  - keyutils=1.6.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libarchive=3.6.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.1.1
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libiconv=1.17
  - libmamba=1.4.2
  - libmambapy=1.4.2
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libsodium=1.0.18
  - libsolv=0.7.23
  - libsqlite=3.42.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libuuid=2.38.1
  - libuv=1.44.2
  - libxml2=2.11.4
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - lzo=2.10
  - mako=1.2.4
  - mamba=1.4.2
  - markupsafe=2.1.2
  - matplotlib-inline=0.1.6
  - mistune=2.0.5
  - nbclassic=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.4.0
  - nbconvert-core=7.4.0
  - nbconvert-pandoc=7.4.0
  - nbformat=5.8.0
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - nodejs=18.15.0
  - notebook=6.5.4
  - notebook-shim=0.2.3
  - oauthlib=3.2.2
  - openssl=3.1.0
  - overrides=7.3.1
  - pamela=1.0.0
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pkgutil-resolve-name=1.3.10
  - pluggy=1.0.0
  - prometheus_client=0.17.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11-abi=4
  - pycosat=0.6.4
  - pycparser=2.21
  - pycurl=7.45.1
  - pygments=2.15.1
  - pyjwt=2.7.0
  - pyopenssl=23.1.1
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - python=3.10.11
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.17.1
  - python-json-logger=2.0.7
  - python_abi=3.10
  - pytz=2023.3
  - pyzmq=25.0.2
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - ruamel.yaml=0.17.29
  - ruamel.yaml.clib=0.2.7
  - send2trash=1.8.2
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - sqlalchemy=2.0.15
  - stack_data=0.6.2
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - toolz=0.12.0
  - traitlets=5.9.0
  - typing_utils=0.1.0
  - urllib3=2.0.2
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.2
  - wheel=0.40.0
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.2
  - pip:
      - aiofiles==22.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - aiosqlite==0.20.0
      - annotated-types==0.7.0
      - ansicolors==1.1.8
      - arcosparse==0.4.2
      - arrow==1.3.0
      - asciitree==0.3.3
      - astropy==6.1.7
      - astropy-iers-data==0.2025.8.25.0.36.58
      - async-timeout==4.0.3
      - boto3==1.40.18
      - botocore==1.40.18
      - bottleneck==1.5.0
      - branca==0.8.1
      - cartopy==0.25.0
      - click==8.1.8
      - cloudpickle==3.1.1
      - cmocean==4.0.3
      - contourpy==1.3.2
      - copernicusmarine==2.2.2
      - cycler==0.12.1
      - dask==2025.7.0
      - diffusers==0.32.2
      - distlib==0.3.8
      - fasteners==0.20
      - filelock==3.15.4
      - folium==0.20.0
      - fonttools==4.59.1
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2025.3.2
      - geopandas==1.0.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - h5netcdf==1.6.4
      - h5py==3.14.0
      - haversine==2.9.0
      - healpy==1.18.1
      - hf-xet==1.1.8
      - huggingface-hub==0.34.4
      - ipykernel==6.30.1
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jinja2==3.0.3
      - jmespath==1.0.1
      - joblib==1.5.1
      - jupyter-resource-usage==0.7.2
      - jupyter-server-fileid==0.9.2
      - jupyter-server-mathjax==0.2.6
      - jupyter-server-proxy==4.2.0
      - jupyter-server-ydoc==0.8.0
      - jupyter-ydoc==0.2.5
      - jupyterlab==3.6.7
      - jupyterlab-git==0.50.1
      - jupyterlab-system-monitor==0.8.0
      - jupyterlab-topbar==0.6.1
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.9
      - locket==1.0.0
      - loguru==0.7.3
      - mapclassify==2.8.1
      - markdown==3.8.2
      - matplotlib==3.10.1
      - mpmath==1.3.0
      - multidict==6.0.5
      - munch==4.0.0
      - nbdime==4.0.1
      - networkx==3.4.2
      - numcodecs==0.13.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - packaging==25.0
      - pandas==2.2.3
      - papermill==2.6.0
      - partd==1.4.2
      - pillow==11.3.0
      - pip==24.1
      - platformdirs==4.2.2
      - polars==1.26.0
      - pooch==1.8.2
      - propcache==0.3.2
      - pyarrow==21.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyerfa==2.0.1.5
      - pyogrio==0.11.1
      - pyparsing==3.2.3
      - pyproj==3.7.1
      - pyshp==2.3.1
      - pystac==1.13.0
      - pyyaml==6.0.2
      - regex==2025.7.34
      - requests==2.32.5
      - s3transfer==0.13.1
      - safetensors==0.6.2
      - scikit-learn==1.7.1
      - scipy==1.11.3
      - semver==3.0.4
      - setuptools==80.9.0
      - shapely==2.0.7
      - simpervisor==1.0.0
      - smmap==5.0.1
      - sympy==1.13.1
      - tenacity==8.4.2
      - threadpoolctl==3.6.0
      - torch==2.6.0
      - tornado==6.4.1
      - tqdm==4.67.1
      - triton==3.2.0
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.13.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - uri-template==1.3.0
      - virtualenv==20.26.3
      - webcolors==24.6.0
      - widgetsnbextension==4.0.14
      - xarray==2025.1.2
      - xyzservices==2025.4.0
      - y-py==0.6.2
      - yarl==1.20.1
      - ypy-websocket==0.8.4
      - zarr==2.18.3
